// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "cal_mag_phase.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cal_mag_phase::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cal_mag_phase::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> cal_mag_phase::ap_ST_st1_fsm_0 = "00000";
const sc_lv<5> cal_mag_phase::ap_ST_st2_fsm_1 = "1";
const sc_lv<5> cal_mag_phase::ap_ST_st3_fsm_2 = "10";
const sc_lv<5> cal_mag_phase::ap_ST_st4_fsm_3 = "11";
const sc_lv<5> cal_mag_phase::ap_ST_st5_fsm_4 = "100";
const sc_lv<5> cal_mag_phase::ap_ST_st6_fsm_5 = "101";
const sc_lv<5> cal_mag_phase::ap_ST_st7_fsm_6 = "110";
const sc_lv<5> cal_mag_phase::ap_ST_st8_fsm_7 = "111";
const sc_lv<5> cal_mag_phase::ap_ST_st9_fsm_8 = "1000";
const sc_lv<5> cal_mag_phase::ap_ST_st10_fsm_9 = "1001";
const sc_lv<5> cal_mag_phase::ap_ST_st11_fsm_10 = "1010";
const sc_lv<5> cal_mag_phase::ap_ST_st12_fsm_11 = "1011";
const sc_lv<5> cal_mag_phase::ap_ST_st13_fsm_12 = "1100";
const sc_lv<5> cal_mag_phase::ap_ST_st14_fsm_13 = "1101";
const sc_lv<5> cal_mag_phase::ap_ST_st15_fsm_14 = "1110";
const sc_lv<5> cal_mag_phase::ap_ST_st16_fsm_15 = "1111";
const sc_lv<5> cal_mag_phase::ap_ST_st17_fsm_16 = "10000";
const sc_lv<5> cal_mag_phase::ap_ST_st18_fsm_17 = "10001";
const sc_lv<5> cal_mag_phase::ap_ST_st19_fsm_18 = "10010";
const sc_lv<5> cal_mag_phase::ap_ST_st20_fsm_19 = "10011";
const sc_lv<5> cal_mag_phase::ap_ST_st21_fsm_20 = "10100";
const sc_lv<5> cal_mag_phase::ap_ST_st22_fsm_21 = "10101";
const sc_lv<5> cal_mag_phase::ap_ST_st23_fsm_22 = "10110";
const sc_lv<1> cal_mag_phase::ap_const_lv1_0 = "0";
const sc_lv<11> cal_mag_phase::ap_const_lv11_0 = "00000000000";
const sc_lv<7> cal_mag_phase::ap_const_lv7_0 = "0000000";
const sc_lv<32> cal_mag_phase::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cal_mag_phase::ap_const_lv32_FFE6DE05 = "11111111111001101101111000000101";
const sc_lv<32> cal_mag_phase::ap_const_lv32_1921FB = "110010010000111111011";
const sc_lv<32> cal_mag_phase::ap_const_lv32_14 = "10100";
const sc_lv<32> cal_mag_phase::ap_const_lv32_33 = "110011";
const sc_lv<11> cal_mag_phase::ap_const_lv11_400 = "10000000000";
const sc_lv<11> cal_mag_phase::ap_const_lv11_1 = "1";
const sc_lv<32> cal_mag_phase::ap_const_lv32_1F = "11111";
const sc_lv<20> cal_mag_phase::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<52> cal_mag_phase::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<53> cal_mag_phase::ap_const_lv53_0 = "00000000000000000000000000000000000000000000000000000";
const sc_lv<22> cal_mag_phase::ap_const_lv22_100000 = "100000000000000000000";
const sc_lv<22> cal_mag_phase::ap_const_lv22_300000 = "1100000000000000000000";
const sc_lv<7> cal_mag_phase::ap_const_lv7_40 = "1000000";
const sc_lv<7> cal_mag_phase::ap_const_lv7_1 = "1";
const sc_lv<105> cal_mag_phase::ap_const_lv105_136E9DEABB71F9 = "10011011011101001110111101010101110110111000111111001";
const sc_lv<105> cal_mag_phase::ap_const_lv105_0 = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> cal_mag_phase::ap_const_lv32_49 = "1001001";
const sc_lv<32> cal_mag_phase::ap_const_lv32_68 = "1101000";
const sc_lv<32> cal_mag_phase::ap_const_lv32_3243F6 = "1100100100001111110110";
const sc_lv<32> cal_mag_phase::ap_const_lv32_FFCDBC0A = "11111111110011011011110000001010";

cal_mag_phase::cal_mag_phase(sc_module_name name) : sc_module(name), mVcdFile(0) {
    cordic_ctab_V_U = new cal_mag_phase_cordic_ctab_V("cordic_ctab_V_U");
    cordic_ctab_V_U->clk(ap_clk);
    cordic_ctab_V_U->reset(ap_rst);
    cordic_ctab_V_U->address0(cordic_ctab_V_address0);
    cordic_ctab_V_U->ce0(cordic_ctab_V_ce0);
    cordic_ctab_V_U->q0(cordic_ctab_V_q0);
    combine_mul_52s_53ns_105_11_U16 = new combine_mul_52s_53ns_105_11<16,11,52,53,105>("combine_mul_52s_53ns_105_11_U16");
    combine_mul_52s_53ns_105_11_U16->clk(ap_clk);
    combine_mul_52s_53ns_105_11_U16->reset(ap_rst);
    combine_mul_52s_53ns_105_11_U16->din0(grp_fu_410_p0);
    combine_mul_52s_53ns_105_11_U16->din1(grp_fu_410_p1);
    combine_mul_52s_53ns_105_11_U16->ce(grp_fu_410_ce);
    combine_mul_52s_53ns_105_11_U16->dout(grp_fu_410_p2);
    combine_mul_32s_22s_54_3_U17 = new combine_mul_32s_22s_54_3<17,3,32,22,54>("combine_mul_32s_22s_54_3_U17");
    combine_mul_32s_22s_54_3_U17->clk(ap_clk);
    combine_mul_32s_22s_54_3_U17->reset(ap_rst);
    combine_mul_32s_22s_54_3_U17->din0(grp_fu_431_p0);
    combine_mul_32s_22s_54_3_U17->din1(grp_fu_431_p1);
    combine_mul_32s_22s_54_3_U17->ce(grp_fu_431_ce);
    combine_mul_32s_22s_54_3_U17->dout(grp_fu_431_p2);
    combine_mul_32s_22s_54_3_U18 = new combine_mul_32s_22s_54_3<18,3,32,22,54>("combine_mul_32s_22s_54_3_U18");
    combine_mul_32s_22s_54_3_U18->clk(ap_clk);
    combine_mul_32s_22s_54_3_U18->reset(ap_rst);
    combine_mul_32s_22s_54_3_U18->din0(grp_fu_440_p0);
    combine_mul_32s_22s_54_3_U18->din1(grp_fu_440_p1);
    combine_mul_32s_22s_54_3_U18->ce(grp_fu_440_ce);
    combine_mul_32s_22s_54_3_U18->dout(grp_fu_440_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP2_V_cast_fu_428_p1);
    sensitive << ( r_V_7_reg_805 );

    SC_METHOD(thread_ai_V_2_fu_513_p3);
    sensitive << ( tmp_30_fu_505_p3 );

    SC_METHOD(thread_ai_V_fu_368_p3);
    sensitive << ( tmp_28_fu_360_p3 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond6_fu_274_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond6_fu_274_p2 );

    SC_METHOD(thread_ap_sig_bdd_573);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond5_fu_583_p2 );

    SC_METHOD(thread_ap_sig_bdd_577);
    sensitive << ( tmp_27_reg_778 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( tmp_32_fu_664_p3 );

    SC_METHOD(thread_ap_sig_bdd_580);
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( tmp_32_fu_664_p3 );
    sensitive << ( or_cond_fu_688_p2 );

    SC_METHOD(thread_ap_sig_bdd_582);
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( tmp_32_fu_664_p3 );
    sensitive << ( or_cond_fu_688_p2 );

    SC_METHOD(thread_ap_sig_bdd_584);
    sensitive << ( tmp_27_reg_778 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( tmp_32_fu_664_p3 );

    SC_METHOD(thread_cordic_ctab_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_6_i_fu_631_p1 );

    SC_METHOD(thread_cordic_ctab_V_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond5_fu_583_p2 );

    SC_METHOD(thread_exitcond5_fu_583_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( step_2_reg_252 );

    SC_METHOD(thread_exitcond6_fu_274_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( i_reg_163 );

    SC_METHOD(thread_exitcond_fu_376_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( i_2_reg_210 );

    SC_METHOD(thread_grp_fu_264_p4);
    sensitive << ( p_Val2_106_in_in_i_reg_182 );

    SC_METHOD(thread_grp_fu_410_ce);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_376_p2 );

    SC_METHOD(thread_grp_fu_410_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_376_p2 );
    sensitive << ( t_V_fu_398_p3 );

    SC_METHOD(thread_grp_fu_410_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_376_p2 );

    SC_METHOD(thread_grp_fu_431_ce);

    SC_METHOD(thread_grp_fu_431_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_Val2_24_reg_200 );

    SC_METHOD(thread_grp_fu_431_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( OP2_V_cast_fu_428_p1 );

    SC_METHOD(thread_grp_fu_440_ce);

    SC_METHOD(thread_grp_fu_440_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_22_reg_810 );

    SC_METHOD(thread_grp_fu_440_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( OP2_V_cast_fu_428_p1 );

    SC_METHOD(thread_i_3_fu_280_p2);
    sensitive << ( i_reg_163 );

    SC_METHOD(thread_i_4_fu_382_p2);
    sensitive << ( i_2_reg_210 );

    SC_METHOD(thread_imag_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_reg_736 );

    SC_METHOD(thread_imag_V_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_lhs_V_1_cast_fu_481_p1);
    sensitive << ( lhs_V_1_fu_473_p3 );

    SC_METHOD(thread_lhs_V_1_fu_473_p3);
    sensitive << ( p_Val2_24_reg_200 );

    SC_METHOD(thread_lhs_V_cast_fu_456_p1);
    sensitive << ( lhs_V_fu_449_p3 );

    SC_METHOD(thread_lhs_V_fu_449_p3);
    sensitive << ( tmp_22_reg_810 );

    SC_METHOD(thread_magFrame_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( magFrame_V_addr_reg_766 );

    SC_METHOD(thread_magFrame_V_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_magFrame_V_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_29_reg_821 );
    sensitive << ( tmp_s_reg_874 );
    sensitive << ( neg_ti_i_fu_542_p2 );

    SC_METHOD(thread_magFrame_V_we0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_mf_i_fu_336_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( mt_i_cast_fu_332_p1 );

    SC_METHOD(thread_mf_i_fu_336_p2);
    sensitive << ( mf_i_fu_336_p1 );

    SC_METHOD(thread_mt8_i_cast_fu_307_p2);
    sensitive << ( p_shl_fu_299_p3 );

    SC_METHOD(thread_mt_i_cast_fu_332_p1);
    sensitive << ( mt_i_fu_325_p3 );

    SC_METHOD(thread_mt_i_fu_325_p3);
    sensitive << ( p_Val2_20_reg_756 );

    SC_METHOD(thread_neg_mul_i_fu_521_p2);
    sensitive << ( mul_i_reg_868 );

    SC_METHOD(thread_neg_ti_i_fu_542_p2);
    sensitive << ( tmp_s_reg_874 );

    SC_METHOD(thread_not2_fu_678_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_Val2_20_reg_756 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( exitcond5_fu_583_p2 );
    sensitive << ( tmp_32_fu_664_p3 );

    SC_METHOD(thread_not3_fu_683_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_Val2_21_reg_771 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( exitcond5_fu_583_p2 );
    sensitive << ( tmp_32_fu_664_p3 );

    SC_METHOD(thread_or_cond_fu_688_p2);
    sensitive << ( not2_fu_678_p2 );
    sensitive << ( not3_fu_683_p2 );

    SC_METHOD(thread_p_Val2_7_i_cast_fu_701_p1);
    sensitive << ( cordic_ctab_V_q0 );

    SC_METHOD(thread_p_shl_fu_299_p3);
    sensitive << ( imag_V_q0 );

    SC_METHOD(thread_phaseFrame_V_addr_2_gep_fu_147_p3);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_reg_736 );
    sensitive << ( tmp_27_reg_778 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( exitcond5_fu_583_p2 );
    sensitive << ( tmp_32_fu_664_p3 );

    SC_METHOD(thread_phaseFrame_V_addr_3_gep_fu_137_p3);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_reg_736 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( exitcond5_fu_583_p2 );
    sensitive << ( tmp_32_fu_664_p3 );

    SC_METHOD(thread_phaseFrame_V_addr_gep_fu_155_p3);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_reg_736 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( exitcond5_fu_583_p2 );

    SC_METHOD(thread_phaseFrame_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_reg_736 );
    sensitive << ( tmp_27_reg_778 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( exitcond5_fu_583_p2 );
    sensitive << ( tmp_32_fu_664_p3 );
    sensitive << ( or_cond_fu_688_p2 );
    sensitive << ( phaseFrame_V_addr_3_gep_fu_137_p3 );
    sensitive << ( phaseFrame_V_addr_2_gep_fu_147_p3 );
    sensitive << ( phaseFrame_V_addr_gep_fu_155_p3 );

    SC_METHOD(thread_phaseFrame_V_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_27_reg_778 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( exitcond5_fu_583_p2 );
    sensitive << ( tmp_32_fu_664_p3 );
    sensitive << ( or_cond_fu_688_p2 );

    SC_METHOD(thread_phaseFrame_V_d0);
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( p_Val2_31_reg_221 );
    sensitive << ( r_V_fu_671_p2 );
    sensitive << ( r_V_s_fu_694_p2 );
    sensitive << ( ap_sig_bdd_577 );
    sensitive << ( ap_sig_bdd_580 );
    sensitive << ( ap_sig_bdd_582 );
    sensitive << ( ap_sig_bdd_584 );
    sensitive << ( ap_sig_bdd_573 );

    SC_METHOD(thread_phaseFrame_V_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_27_reg_778 );
    sensitive << ( tmp_i3_reg_880 );
    sensitive << ( exitcond5_fu_583_p2 );
    sensitive << ( tmp_32_fu_664_p3 );
    sensitive << ( or_cond_fu_688_p2 );

    SC_METHOD(thread_r_V_12_i_fu_711_p2);
    sensitive << ( p_Val2_31_reg_221 );
    sensitive << ( p_Val2_7_i_cast_fu_701_p1 );

    SC_METHOD(thread_r_V_17_fu_313_p3);
    sensitive << ( tmp_27_fu_291_p3 );
    sensitive << ( p_shl_fu_299_p3 );
    sensitive << ( mt8_i_cast_fu_307_p2 );

    SC_METHOD(thread_r_V_18_fu_342_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( mt_i_cast_fu_332_p1 );

    SC_METHOD(thread_r_V_18_fu_342_p3);
    sensitive << ( tmp_27_fu_291_p3 );
    sensitive << ( r_V_18_fu_342_p1 );
    sensitive << ( mf_i_fu_336_p2 );

    SC_METHOD(thread_r_V_20_fu_464_p2);
    sensitive << ( lhs_V_cast_fu_456_p1 );
    sensitive << ( rhs_V2_i_fu_460_p1 );

    SC_METHOD(thread_r_V_22_fu_489_p2);
    sensitive << ( lhs_V_1_cast_fu_481_p1 );
    sensitive << ( rhs_V_203_i_fu_485_p1 );

    SC_METHOD(thread_r_V_23_fu_607_p2);
    sensitive << ( p_Val2_29_reg_234 );
    sensitive << ( sh_assign_1_i_cast_fu_603_p1 );

    SC_METHOD(thread_r_V_24_fu_619_p2);
    sensitive << ( t_V_4_reg_243 );
    sensitive << ( sh_assign_1_i_cast_fu_603_p1 );

    SC_METHOD(thread_r_V_48_cast_fu_321_p1);
    sensitive << ( r_V_17_fu_313_p3 );

    SC_METHOD(thread_r_V_7_fu_392_p2);
    sensitive << ( ai_V_1_reg_191 );
    sensitive << ( sh_assign_5_cast_cast_fu_388_p1 );

    SC_METHOD(thread_r_V_fu_671_p2);
    sensitive << ( p_Val2_31_reg_221 );

    SC_METHOD(thread_r_V_i_fu_705_p2);
    sensitive << ( p_Val2_31_reg_221 );
    sensitive << ( p_Val2_7_i_cast_fu_701_p1 );

    SC_METHOD(thread_r_V_s_fu_694_p2);
    sensitive << ( p_Val2_31_reg_221 );

    SC_METHOD(thread_real_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_286_p1 );

    SC_METHOD(thread_real_V_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond6_fu_274_p2 );

    SC_METHOD(thread_rhs_V2_i_fu_460_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( r_V_19_reg_843 );

    SC_METHOD(thread_rhs_V2_i_fu_460_p1);
    sensitive << ( rhs_V2_i_fu_460_p0 );

    SC_METHOD(thread_rhs_V_203_i_fu_485_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( r_V_21_reg_848 );

    SC_METHOD(thread_rhs_V_203_i_fu_485_p1);
    sensitive << ( rhs_V_203_i_fu_485_p0 );

    SC_METHOD(thread_sel_i_fu_526_p3);
    sensitive << ( tmp_29_reg_821 );
    sensitive << ( mul_i_reg_868 );
    sensitive << ( neg_mul_i_fu_521_p2 );

    SC_METHOD(thread_sh_assign_1_i_cast_fu_603_p1);
    sensitive << ( step_2_reg_252 );

    SC_METHOD(thread_sh_assign_5_cast_cast_fu_388_p1);
    sensitive << ( i_2_reg_210 );

    SC_METHOD(thread_step_fu_589_p2);
    sensitive << ( step_2_reg_252 );

    SC_METHOD(thread_storemerge_i_fu_717_p3);
    sensitive << ( tmp_31_reg_902 );
    sensitive << ( r_V_i_fu_705_p2 );
    sensitive << ( r_V_12_i_fu_711_p2 );

    SC_METHOD(thread_t_V_fu_398_p3);
    sensitive << ( grp_fu_264_p4 );

    SC_METHOD(thread_tmp_27_fu_291_p3);
    sensitive << ( imag_V_q0 );

    SC_METHOD(thread_tmp_28_fu_360_p3);
    sensitive << ( r_V_18_fu_342_p3 );

    SC_METHOD(thread_tmp_30_fu_505_p3);
    sensitive << ( r_V_22_fu_489_p2 );

    SC_METHOD(thread_tmp_31_fu_595_p3);
    sensitive << ( p_Val2_29_reg_234 );

    SC_METHOD(thread_tmp_32_fu_664_p3);
    sensitive << ( p_Val2_20_reg_756 );

    SC_METHOD(thread_tmp_6_i_fu_631_p1);
    sensitive << ( step_2_reg_252 );

    SC_METHOD(thread_tmp_fu_286_p1);
    sensitive << ( i_reg_163 );

    SC_METHOD(thread_tmp_i3_fu_554_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_Val2_20_reg_756 );

    SC_METHOD(thread_x_iteration_V_1_fu_576_p3);
    sensitive << ( p_Val2_20_reg_756 );
    sensitive << ( tmp_i3_fu_554_p2 );
    sensitive << ( x_iteration_V_fu_559_p2 );

    SC_METHOD(thread_x_iteration_V_3_fu_613_p2);
    sensitive << ( t_V_4_reg_243 );
    sensitive << ( r_V_23_fu_607_p2 );

    SC_METHOD(thread_x_iteration_V_4_fu_636_p2);
    sensitive << ( t_V_4_reg_243 );
    sensitive << ( r_V_23_fu_607_p2 );

    SC_METHOD(thread_x_iteration_V_5_fu_656_p3);
    sensitive << ( tmp_31_fu_595_p3 );
    sensitive << ( x_iteration_V_3_fu_613_p2 );
    sensitive << ( x_iteration_V_4_fu_636_p2 );

    SC_METHOD(thread_x_iteration_V_fu_559_p2);
    sensitive << ( p_Val2_20_reg_756 );

    SC_METHOD(thread_y_iteration_V_1_fu_564_p2);
    sensitive << ( p_Val2_21_reg_771 );

    SC_METHOD(thread_y_iteration_V_2_fu_569_p3);
    sensitive << ( p_Val2_21_reg_771 );
    sensitive << ( tmp_i3_fu_554_p2 );
    sensitive << ( y_iteration_V_1_fu_564_p2 );

    SC_METHOD(thread_y_iteration_V_4_fu_642_p2);
    sensitive << ( p_Val2_29_reg_234 );
    sensitive << ( r_V_24_fu_619_p2 );

    SC_METHOD(thread_y_iteration_V_5_fu_648_p3);
    sensitive << ( tmp_31_fu_595_p3 );
    sensitive << ( y_iteration_V_fu_625_p2 );
    sensitive << ( y_iteration_V_4_fu_642_p2 );

    SC_METHOD(thread_y_iteration_V_fu_625_p2);
    sensitive << ( p_Val2_29_reg_234 );
    sensitive << ( r_V_24_fu_619_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond6_fu_274_p2 );
    sensitive << ( exitcond_fu_376_p2 );
    sensitive << ( exitcond5_fu_583_p2 );

    ap_CS_fsm = "00000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cal_mag_phase_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, magFrame_V_address0, "(port)magFrame_V_address0");
    sc_trace(mVcdFile, magFrame_V_ce0, "(port)magFrame_V_ce0");
    sc_trace(mVcdFile, magFrame_V_we0, "(port)magFrame_V_we0");
    sc_trace(mVcdFile, magFrame_V_d0, "(port)magFrame_V_d0");
    sc_trace(mVcdFile, phaseFrame_V_address0, "(port)phaseFrame_V_address0");
    sc_trace(mVcdFile, phaseFrame_V_ce0, "(port)phaseFrame_V_ce0");
    sc_trace(mVcdFile, phaseFrame_V_we0, "(port)phaseFrame_V_we0");
    sc_trace(mVcdFile, phaseFrame_V_d0, "(port)phaseFrame_V_d0");
    sc_trace(mVcdFile, real_V_address0, "(port)real_V_address0");
    sc_trace(mVcdFile, real_V_ce0, "(port)real_V_ce0");
    sc_trace(mVcdFile, real_V_q0, "(port)real_V_q0");
    sc_trace(mVcdFile, imag_V_address0, "(port)imag_V_address0");
    sc_trace(mVcdFile, imag_V_ce0, "(port)imag_V_ce0");
    sc_trace(mVcdFile, imag_V_q0, "(port)imag_V_q0");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, cordic_ctab_V_address0, "cordic_ctab_V_address0");
    sc_trace(mVcdFile, cordic_ctab_V_ce0, "cordic_ctab_V_ce0");
    sc_trace(mVcdFile, cordic_ctab_V_q0, "cordic_ctab_V_q0");
    sc_trace(mVcdFile, i_3_fu_280_p2, "i_3_fu_280_p2");
    sc_trace(mVcdFile, i_3_reg_727, "i_3_reg_727");
    sc_trace(mVcdFile, tmp_fu_286_p1, "tmp_fu_286_p1");
    sc_trace(mVcdFile, tmp_reg_736, "tmp_reg_736");
    sc_trace(mVcdFile, exitcond6_fu_274_p2, "exitcond6_fu_274_p2");
    sc_trace(mVcdFile, p_Val2_20_reg_756, "p_Val2_20_reg_756");
    sc_trace(mVcdFile, magFrame_V_addr_reg_766, "magFrame_V_addr_reg_766");
    sc_trace(mVcdFile, p_Val2_21_reg_771, "p_Val2_21_reg_771");
    sc_trace(mVcdFile, tmp_27_fu_291_p3, "tmp_27_fu_291_p3");
    sc_trace(mVcdFile, tmp_27_reg_778, "tmp_27_reg_778");
    sc_trace(mVcdFile, r_V_48_cast_fu_321_p1, "r_V_48_cast_fu_321_p1");
    sc_trace(mVcdFile, ai_V_fu_368_p3, "ai_V_fu_368_p3");
    sc_trace(mVcdFile, i_4_fu_382_p2, "i_4_fu_382_p2");
    sc_trace(mVcdFile, i_4_reg_800, "i_4_reg_800");
    sc_trace(mVcdFile, r_V_7_fu_392_p2, "r_V_7_fu_392_p2");
    sc_trace(mVcdFile, r_V_7_reg_805, "r_V_7_reg_805");
    sc_trace(mVcdFile, exitcond_fu_376_p2, "exitcond_fu_376_p2");
    sc_trace(mVcdFile, grp_fu_264_p4, "grp_fu_264_p4");
    sc_trace(mVcdFile, tmp_22_reg_810, "tmp_22_reg_810");
    sc_trace(mVcdFile, tmp_29_reg_821, "tmp_29_reg_821");
    sc_trace(mVcdFile, OP2_V_cast_fu_428_p1, "OP2_V_cast_fu_428_p1");
    sc_trace(mVcdFile, grp_fu_431_p2, "grp_fu_431_p2");
    sc_trace(mVcdFile, r_V_19_reg_843, "r_V_19_reg_843");
    sc_trace(mVcdFile, grp_fu_440_p2, "grp_fu_440_p2");
    sc_trace(mVcdFile, r_V_21_reg_848, "r_V_21_reg_848");
    sc_trace(mVcdFile, r_V_20_fu_464_p2, "r_V_20_fu_464_p2");
    sc_trace(mVcdFile, ai_V_2_fu_513_p3, "ai_V_2_fu_513_p3");
    sc_trace(mVcdFile, grp_fu_410_p2, "grp_fu_410_p2");
    sc_trace(mVcdFile, mul_i_reg_868, "mul_i_reg_868");
    sc_trace(mVcdFile, tmp_s_reg_874, "tmp_s_reg_874");
    sc_trace(mVcdFile, tmp_i3_fu_554_p2, "tmp_i3_fu_554_p2");
    sc_trace(mVcdFile, tmp_i3_reg_880, "tmp_i3_reg_880");
    sc_trace(mVcdFile, y_iteration_V_2_fu_569_p3, "y_iteration_V_2_fu_569_p3");
    sc_trace(mVcdFile, x_iteration_V_1_fu_576_p3, "x_iteration_V_1_fu_576_p3");
    sc_trace(mVcdFile, step_fu_589_p2, "step_fu_589_p2");
    sc_trace(mVcdFile, step_reg_897, "step_reg_897");
    sc_trace(mVcdFile, tmp_31_fu_595_p3, "tmp_31_fu_595_p3");
    sc_trace(mVcdFile, tmp_31_reg_902, "tmp_31_reg_902");
    sc_trace(mVcdFile, exitcond5_fu_583_p2, "exitcond5_fu_583_p2");
    sc_trace(mVcdFile, y_iteration_V_5_fu_648_p3, "y_iteration_V_5_fu_648_p3");
    sc_trace(mVcdFile, y_iteration_V_5_reg_912, "y_iteration_V_5_reg_912");
    sc_trace(mVcdFile, x_iteration_V_5_fu_656_p3, "x_iteration_V_5_fu_656_p3");
    sc_trace(mVcdFile, x_iteration_V_5_reg_917, "x_iteration_V_5_reg_917");
    sc_trace(mVcdFile, storemerge_i_fu_717_p3, "storemerge_i_fu_717_p3");
    sc_trace(mVcdFile, i_reg_163, "i_reg_163");
    sc_trace(mVcdFile, tmp_32_fu_664_p3, "tmp_32_fu_664_p3");
    sc_trace(mVcdFile, or_cond_fu_688_p2, "or_cond_fu_688_p2");
    sc_trace(mVcdFile, p_Val2_106_in_in_i_reg_182, "p_Val2_106_in_in_i_reg_182");
    sc_trace(mVcdFile, ai_V_1_reg_191, "ai_V_1_reg_191");
    sc_trace(mVcdFile, p_Val2_24_reg_200, "p_Val2_24_reg_200");
    sc_trace(mVcdFile, i_2_reg_210, "i_2_reg_210");
    sc_trace(mVcdFile, p_Val2_31_reg_221, "p_Val2_31_reg_221");
    sc_trace(mVcdFile, p_Val2_29_reg_234, "p_Val2_29_reg_234");
    sc_trace(mVcdFile, t_V_4_reg_243, "t_V_4_reg_243");
    sc_trace(mVcdFile, step_2_reg_252, "step_2_reg_252");
    sc_trace(mVcdFile, tmp_6_i_fu_631_p1, "tmp_6_i_fu_631_p1");
    sc_trace(mVcdFile, phaseFrame_V_addr_3_gep_fu_137_p3, "phaseFrame_V_addr_3_gep_fu_137_p3");
    sc_trace(mVcdFile, phaseFrame_V_addr_2_gep_fu_147_p3, "phaseFrame_V_addr_2_gep_fu_147_p3");
    sc_trace(mVcdFile, phaseFrame_V_addr_gep_fu_155_p3, "phaseFrame_V_addr_gep_fu_155_p3");
    sc_trace(mVcdFile, r_V_fu_671_p2, "r_V_fu_671_p2");
    sc_trace(mVcdFile, r_V_s_fu_694_p2, "r_V_s_fu_694_p2");
    sc_trace(mVcdFile, p_shl_fu_299_p3, "p_shl_fu_299_p3");
    sc_trace(mVcdFile, mt8_i_cast_fu_307_p2, "mt8_i_cast_fu_307_p2");
    sc_trace(mVcdFile, r_V_17_fu_313_p3, "r_V_17_fu_313_p3");
    sc_trace(mVcdFile, mt_i_fu_325_p3, "mt_i_fu_325_p3");
    sc_trace(mVcdFile, mf_i_fu_336_p1, "mf_i_fu_336_p1");
    sc_trace(mVcdFile, mt_i_cast_fu_332_p1, "mt_i_cast_fu_332_p1");
    sc_trace(mVcdFile, r_V_18_fu_342_p1, "r_V_18_fu_342_p1");
    sc_trace(mVcdFile, mf_i_fu_336_p2, "mf_i_fu_336_p2");
    sc_trace(mVcdFile, r_V_18_fu_342_p3, "r_V_18_fu_342_p3");
    sc_trace(mVcdFile, tmp_28_fu_360_p3, "tmp_28_fu_360_p3");
    sc_trace(mVcdFile, sh_assign_5_cast_cast_fu_388_p1, "sh_assign_5_cast_cast_fu_388_p1");
    sc_trace(mVcdFile, t_V_fu_398_p3, "t_V_fu_398_p3");
    sc_trace(mVcdFile, grp_fu_410_p0, "grp_fu_410_p0");
    sc_trace(mVcdFile, grp_fu_410_p1, "grp_fu_410_p1");
    sc_trace(mVcdFile, grp_fu_431_p0, "grp_fu_431_p0");
    sc_trace(mVcdFile, grp_fu_431_p1, "grp_fu_431_p1");
    sc_trace(mVcdFile, grp_fu_440_p0, "grp_fu_440_p0");
    sc_trace(mVcdFile, grp_fu_440_p1, "grp_fu_440_p1");
    sc_trace(mVcdFile, lhs_V_fu_449_p3, "lhs_V_fu_449_p3");
    sc_trace(mVcdFile, rhs_V2_i_fu_460_p0, "rhs_V2_i_fu_460_p0");
    sc_trace(mVcdFile, lhs_V_cast_fu_456_p1, "lhs_V_cast_fu_456_p1");
    sc_trace(mVcdFile, rhs_V2_i_fu_460_p1, "rhs_V2_i_fu_460_p1");
    sc_trace(mVcdFile, lhs_V_1_fu_473_p3, "lhs_V_1_fu_473_p3");
    sc_trace(mVcdFile, rhs_V_203_i_fu_485_p0, "rhs_V_203_i_fu_485_p0");
    sc_trace(mVcdFile, lhs_V_1_cast_fu_481_p1, "lhs_V_1_cast_fu_481_p1");
    sc_trace(mVcdFile, rhs_V_203_i_fu_485_p1, "rhs_V_203_i_fu_485_p1");
    sc_trace(mVcdFile, r_V_22_fu_489_p2, "r_V_22_fu_489_p2");
    sc_trace(mVcdFile, tmp_30_fu_505_p3, "tmp_30_fu_505_p3");
    sc_trace(mVcdFile, neg_mul_i_fu_521_p2, "neg_mul_i_fu_521_p2");
    sc_trace(mVcdFile, sel_i_fu_526_p3, "sel_i_fu_526_p3");
    sc_trace(mVcdFile, neg_ti_i_fu_542_p2, "neg_ti_i_fu_542_p2");
    sc_trace(mVcdFile, y_iteration_V_1_fu_564_p2, "y_iteration_V_1_fu_564_p2");
    sc_trace(mVcdFile, x_iteration_V_fu_559_p2, "x_iteration_V_fu_559_p2");
    sc_trace(mVcdFile, sh_assign_1_i_cast_fu_603_p1, "sh_assign_1_i_cast_fu_603_p1");
    sc_trace(mVcdFile, r_V_23_fu_607_p2, "r_V_23_fu_607_p2");
    sc_trace(mVcdFile, r_V_24_fu_619_p2, "r_V_24_fu_619_p2");
    sc_trace(mVcdFile, y_iteration_V_fu_625_p2, "y_iteration_V_fu_625_p2");
    sc_trace(mVcdFile, y_iteration_V_4_fu_642_p2, "y_iteration_V_4_fu_642_p2");
    sc_trace(mVcdFile, x_iteration_V_3_fu_613_p2, "x_iteration_V_3_fu_613_p2");
    sc_trace(mVcdFile, x_iteration_V_4_fu_636_p2, "x_iteration_V_4_fu_636_p2");
    sc_trace(mVcdFile, not2_fu_678_p2, "not2_fu_678_p2");
    sc_trace(mVcdFile, not3_fu_683_p2, "not3_fu_683_p2");
    sc_trace(mVcdFile, p_Val2_7_i_cast_fu_701_p1, "p_Val2_7_i_cast_fu_701_p1");
    sc_trace(mVcdFile, r_V_i_fu_705_p2, "r_V_i_fu_705_p2");
    sc_trace(mVcdFile, r_V_12_i_fu_711_p2, "r_V_12_i_fu_711_p2");
    sc_trace(mVcdFile, grp_fu_410_ce, "grp_fu_410_ce");
    sc_trace(mVcdFile, grp_fu_431_ce, "grp_fu_431_ce");
    sc_trace(mVcdFile, grp_fu_440_ce, "grp_fu_440_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_577, "ap_sig_bdd_577");
    sc_trace(mVcdFile, ap_sig_bdd_580, "ap_sig_bdd_580");
    sc_trace(mVcdFile, ap_sig_bdd_582, "ap_sig_bdd_582");
    sc_trace(mVcdFile, ap_sig_bdd_584, "ap_sig_bdd_584");
    sc_trace(mVcdFile, ap_sig_bdd_573, "ap_sig_bdd_573");

    }
}

cal_mag_phase::~cal_mag_phase() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete cordic_ctab_V_U;
    delete combine_mul_52s_53ns_105_11_U16;
    delete combine_mul_32s_22s_54_3_U17;
    delete combine_mul_32s_22s_54_3_U18;
}

void cal_mag_phase::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read())) {
        ai_V_1_reg_191 = ai_V_2_fu_513_p3.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        ai_V_1_reg_191 = ai_V_fu_368_p3.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read())) {
        i_2_reg_210 = i_4_reg_800.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        i_2_reg_210 = ap_const_lv7_0;
    }
    if (((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read())))) {
        i_reg_163 = i_3_reg_727.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_163 = ap_const_lv11_0;
    }
    if (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read())) {
        p_Val2_106_in_in_i_reg_182 = r_V_20_fu_464_p2.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        p_Val2_106_in_in_i_reg_182 = r_V_48_cast_fu_321_p1.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read())) {
        p_Val2_24_reg_200 = r_V_22_fu_489_p2.read().range(51, 20);
    } else if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        p_Val2_24_reg_200 = r_V_18_fu_342_p3.read().range(51, 20);
    }
    if (esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) {
        p_Val2_29_reg_234 = y_iteration_V_5_reg_912.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        p_Val2_29_reg_234 = y_iteration_V_2_fu_569_p3.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) {
        p_Val2_31_reg_221 = storemerge_i_fu_717_p3.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        p_Val2_31_reg_221 = ap_const_lv32_0;
    }
    if (esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) {
        step_2_reg_252 = step_reg_897.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        step_2_reg_252 = ap_const_lv7_0;
    }
    if (esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) {
        t_V_4_reg_243 = x_iteration_V_5_reg_917.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        t_V_4_reg_243 = x_iteration_V_1_fu_576_p3.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        i_3_reg_727 = i_3_fu_280_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read())) {
        i_4_reg_800 = i_4_fu_382_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        magFrame_V_addr_reg_766 =  (sc_lv<10>) (tmp_reg_736.read());
        p_Val2_21_reg_771 = imag_V_q0.read();
        tmp_27_reg_778 = imag_V_q0.read().range(31, 31);
    }
    if (esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        mul_i_reg_868 = grp_fu_410_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        p_Val2_20_reg_756 = real_V_q0.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read())) {
        r_V_19_reg_843 = grp_fu_431_p2.read();
        r_V_21_reg_848 = grp_fu_440_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_376_p2.read()))) {
        r_V_7_reg_805 = r_V_7_fu_392_p2.read();
        tmp_22_reg_810 = p_Val2_106_in_in_i_reg_182.read().range(51, 20);
    }
    if (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read())) {
        step_reg_897 = step_fu_589_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_376_p2.read()))) {
        tmp_29_reg_821 = p_Val2_106_in_in_i_reg_182.read().range(51, 51);
    }
    if ((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()))) {
        tmp_31_reg_902 = p_Val2_29_reg_234.read().range(31, 31);
        x_iteration_V_5_reg_917 = x_iteration_V_5_fu_656_p3.read();
        y_iteration_V_5_reg_912 = y_iteration_V_5_fu_648_p3.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        tmp_i3_reg_880 = tmp_i3_fu_554_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && esl_seteq<1,1,1>(exitcond6_fu_274_p2.read(), ap_const_lv1_0))) {
        tmp_reg_736 = tmp_fu_286_p1.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read())) {
        tmp_s_reg_874 = sel_i_fu_526_p3.read().range(104, 73);
    }
}

void cal_mag_phase::thread_OP2_V_cast_fu_428_p1() {
    OP2_V_cast_fu_428_p1 = esl_sext<54,22>(r_V_7_reg_805.read());
}

void cal_mag_phase::thread_ai_V_2_fu_513_p3() {
    ai_V_2_fu_513_p3 = (!tmp_30_fu_505_p3.read()[0].is_01())? sc_lv<22>(): ((tmp_30_fu_505_p3.read()[0].to_bool())? ap_const_lv22_100000: ap_const_lv22_300000);
}

void cal_mag_phase::thread_ai_V_fu_368_p3() {
    ai_V_fu_368_p3 = (!tmp_28_fu_360_p3.read()[0].is_01())? sc_lv<22>(): ((tmp_28_fu_360_p3.read()[0].to_bool())? ap_const_lv22_100000: ap_const_lv22_300000);
}

void cal_mag_phase::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(exitcond6_fu_274_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_ap_ready() {
    if ((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond6_fu_274_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_ap_sig_bdd_573() {
    ap_sig_bdd_573 = (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()));
}

void cal_mag_phase::thread_ap_sig_bdd_577() {
    ap_sig_bdd_577 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read()));
}

void cal_mag_phase::thread_ap_sig_bdd_580() {
    ap_sig_bdd_580 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read()));
}

void cal_mag_phase::thread_ap_sig_bdd_582() {
    ap_sig_bdd_582 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read()));
}

void cal_mag_phase::thread_ap_sig_bdd_584() {
    ap_sig_bdd_584 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read()));
}

void cal_mag_phase::thread_cordic_ctab_V_address0() {
    cordic_ctab_V_address0 =  (sc_lv<6>) (tmp_6_i_fu_631_p1.read());
}

void cal_mag_phase::thread_cordic_ctab_V_ce0() {
    if ((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()))) {
        cordic_ctab_V_ce0 = ap_const_logic_1;
    } else {
        cordic_ctab_V_ce0 = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_exitcond5_fu_583_p2() {
    exitcond5_fu_583_p2 = (!step_2_reg_252.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(step_2_reg_252.read() == ap_const_lv7_40);
}

void cal_mag_phase::thread_exitcond6_fu_274_p2() {
    exitcond6_fu_274_p2 = (!i_reg_163.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_163.read() == ap_const_lv11_400);
}

void cal_mag_phase::thread_exitcond_fu_376_p2() {
    exitcond_fu_376_p2 = (!i_2_reg_210.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_210.read() == ap_const_lv7_40);
}

void cal_mag_phase::thread_grp_fu_264_p4() {
    grp_fu_264_p4 = p_Val2_106_in_in_i_reg_182.read().range(51, 20);
}

void cal_mag_phase::thread_grp_fu_410_ce() {
    if (((esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_376_p2.read())) || 
         esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st11_fsm_10, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read()))) {
        grp_fu_410_ce = ap_const_logic_1;
    } else {
        grp_fu_410_ce = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_grp_fu_410_p0() {
    grp_fu_410_p0 = t_V_fu_398_p3.read();
}

void cal_mag_phase::thread_grp_fu_410_p1() {
    grp_fu_410_p1 =  (sc_lv<53>) (ap_const_lv105_136E9DEABB71F9);
}

void cal_mag_phase::thread_grp_fu_431_ce() {
    grp_fu_431_ce = ap_const_logic_1;
}

void cal_mag_phase::thread_grp_fu_431_p0() {
    grp_fu_431_p0 = p_Val2_24_reg_200.read();
}

void cal_mag_phase::thread_grp_fu_431_p1() {
    grp_fu_431_p1 =  (sc_lv<22>) (OP2_V_cast_fu_428_p1.read());
}

void cal_mag_phase::thread_grp_fu_440_ce() {
    grp_fu_440_ce = ap_const_logic_1;
}

void cal_mag_phase::thread_grp_fu_440_p0() {
    grp_fu_440_p0 = tmp_22_reg_810.read();
}

void cal_mag_phase::thread_grp_fu_440_p1() {
    grp_fu_440_p1 =  (sc_lv<22>) (OP2_V_cast_fu_428_p1.read());
}

void cal_mag_phase::thread_i_3_fu_280_p2() {
    i_3_fu_280_p2 = (!i_reg_163.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_bigint<11>(i_reg_163.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void cal_mag_phase::thread_i_4_fu_382_p2() {
    i_4_fu_382_p2 = (!i_2_reg_210.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_bigint<7>(i_2_reg_210.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void cal_mag_phase::thread_imag_V_address0() {
    imag_V_address0 =  (sc_lv<10>) (tmp_reg_736.read());
}

void cal_mag_phase::thread_imag_V_ce0() {
    if (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        imag_V_ce0 = ap_const_logic_1;
    } else {
        imag_V_ce0 = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_lhs_V_1_cast_fu_481_p1() {
    lhs_V_1_cast_fu_481_p1 = esl_zext<65,52>(lhs_V_1_fu_473_p3.read());
}

void cal_mag_phase::thread_lhs_V_1_fu_473_p3() {
    lhs_V_1_fu_473_p3 = esl_concat<32,20>(p_Val2_24_reg_200.read(), ap_const_lv20_0);
}

void cal_mag_phase::thread_lhs_V_cast_fu_456_p1() {
    lhs_V_cast_fu_456_p1 = esl_zext<65,52>(lhs_V_fu_449_p3.read());
}

void cal_mag_phase::thread_lhs_V_fu_449_p3() {
    lhs_V_fu_449_p3 = esl_concat<32,20>(tmp_22_reg_810.read(), ap_const_lv20_0);
}

void cal_mag_phase::thread_magFrame_V_address0() {
    magFrame_V_address0 = magFrame_V_addr_reg_766.read();
}

void cal_mag_phase::thread_magFrame_V_ce0() {
    if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        magFrame_V_ce0 = ap_const_logic_1;
    } else {
        magFrame_V_ce0 = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_magFrame_V_d0() {
    magFrame_V_d0 = (!tmp_29_reg_821.read()[0].is_01())? sc_lv<32>(): ((tmp_29_reg_821.read()[0].to_bool())? neg_ti_i_fu_542_p2.read(): tmp_s_reg_874.read());
}

void cal_mag_phase::thread_magFrame_V_we0() {
    if ((esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()))) {
        magFrame_V_we0 = ap_const_logic_1;
    } else {
        magFrame_V_we0 = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_mf_i_fu_336_p1() {
    mf_i_fu_336_p1 = mt_i_cast_fu_332_p1.read();
}

void cal_mag_phase::thread_mf_i_fu_336_p2() {
    mf_i_fu_336_p2 = (!ap_const_lv53_0.is_01() || !mf_i_fu_336_p1.read().is_01())? sc_lv<53>(): (sc_bigint<53>(ap_const_lv53_0) - sc_biguint<53>(mf_i_fu_336_p1.read()));
}

void cal_mag_phase::thread_mt8_i_cast_fu_307_p2() {
    mt8_i_cast_fu_307_p2 = (!ap_const_lv52_0.is_01() || !p_shl_fu_299_p3.read().is_01())? sc_lv<52>(): (sc_bigint<52>(ap_const_lv52_0) - sc_biguint<52>(p_shl_fu_299_p3.read()));
}

void cal_mag_phase::thread_mt_i_cast_fu_332_p1() {
    mt_i_cast_fu_332_p1 = esl_sext<53,52>(mt_i_fu_325_p3.read());
}

void cal_mag_phase::thread_mt_i_fu_325_p3() {
    mt_i_fu_325_p3 = esl_concat<32,20>(p_Val2_20_reg_756.read(), ap_const_lv20_0);
}

void cal_mag_phase::thread_neg_mul_i_fu_521_p2() {
    neg_mul_i_fu_521_p2 = (!ap_const_lv105_0.is_01() || !mul_i_reg_868.read().is_01())? sc_lv<105>(): (sc_bigint<105>(ap_const_lv105_0) - sc_biguint<105>(mul_i_reg_868.read()));
}

void cal_mag_phase::thread_neg_ti_i_fu_542_p2() {
    neg_ti_i_fu_542_p2 = (!ap_const_lv32_0.is_01() || !tmp_s_reg_874.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_s_reg_874.read()));
}

void cal_mag_phase::thread_not2_fu_678_p2() {
    not2_fu_678_p2 = (!p_Val2_20_reg_756.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Val2_20_reg_756.read() == ap_const_lv32_0);
}

void cal_mag_phase::thread_not3_fu_683_p2() {
    not3_fu_683_p2 = (!p_Val2_21_reg_771.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(p_Val2_21_reg_771.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void cal_mag_phase::thread_or_cond_fu_688_p2() {
    or_cond_fu_688_p2 = (not2_fu_678_p2.read() & not3_fu_683_p2.read());
}

void cal_mag_phase::thread_p_Val2_7_i_cast_fu_701_p1() {
    p_Val2_7_i_cast_fu_701_p1 = esl_zext<32,20>(cordic_ctab_V_q0.read());
}

void cal_mag_phase::thread_p_shl_fu_299_p3() {
    p_shl_fu_299_p3 = esl_concat<32,20>(imag_V_q0.read(), ap_const_lv20_0);
}

void cal_mag_phase::thread_phaseFrame_V_addr_2_gep_fu_147_p3() {
    phaseFrame_V_addr_2_gep_fu_147_p3 =  (sc_lv<10>) (tmp_reg_736.read());
}

void cal_mag_phase::thread_phaseFrame_V_addr_3_gep_fu_137_p3() {
    phaseFrame_V_addr_3_gep_fu_137_p3 =  (sc_lv<10>) (tmp_reg_736.read());
}

void cal_mag_phase::thread_phaseFrame_V_addr_gep_fu_155_p3() {
    phaseFrame_V_addr_gep_fu_155_p3 =  (sc_lv<10>) (tmp_reg_736.read());
}

void cal_mag_phase::thread_phaseFrame_V_address0() {
    if ((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()))) {
        phaseFrame_V_address0 = phaseFrame_V_addr_gep_fu_155_p3.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read()))) {
        phaseFrame_V_address0 = phaseFrame_V_addr_2_gep_fu_147_p3.read();
    } else if (((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read())))) {
        phaseFrame_V_address0 = phaseFrame_V_addr_3_gep_fu_137_p3.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read()))) {
        phaseFrame_V_address0 =  (sc_lv<10>) (tmp_reg_736.read());
    } else {
        phaseFrame_V_address0 =  (sc_lv<10>) (tmp_reg_736.read());
    }
}

void cal_mag_phase::thread_phaseFrame_V_ce0() {
    if (((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read())))) {
        phaseFrame_V_ce0 = ap_const_logic_1;
    } else {
        phaseFrame_V_ce0 = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_phaseFrame_V_d0() {
    if (ap_sig_bdd_573.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read())) {
            phaseFrame_V_d0 = p_Val2_31_reg_221.read();
        } else if (ap_sig_bdd_584.read()) {
            phaseFrame_V_d0 = r_V_s_fu_694_p2.read();
        } else if (ap_sig_bdd_582.read()) {
            phaseFrame_V_d0 = ap_const_lv32_1921FB;
        } else if (ap_sig_bdd_580.read()) {
            phaseFrame_V_d0 = ap_const_lv32_FFE6DE05;
        } else if (ap_sig_bdd_577.read()) {
            phaseFrame_V_d0 = r_V_fu_671_p2.read();
        } else {
            phaseFrame_V_d0 = r_V_s_fu_694_p2.read();
        }
    } else {
        phaseFrame_V_d0 = r_V_s_fu_694_p2.read();
    }
}

void cal_mag_phase::thread_phaseFrame_V_we0() {
    if (((esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_688_p2.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_664_p3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_778.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i3_reg_880.read())))) {
        phaseFrame_V_we0 = ap_const_logic_1;
    } else {
        phaseFrame_V_we0 = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_r_V_12_i_fu_711_p2() {
    r_V_12_i_fu_711_p2 = (!p_Val2_7_i_cast_fu_701_p1.read().is_01() || !p_Val2_31_reg_221.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_Val2_7_i_cast_fu_701_p1.read()) + sc_biguint<32>(p_Val2_31_reg_221.read()));
}

void cal_mag_phase::thread_r_V_17_fu_313_p3() {
    r_V_17_fu_313_p3 = (!tmp_27_fu_291_p3.read()[0].is_01())? sc_lv<52>(): ((tmp_27_fu_291_p3.read()[0].to_bool())? mt8_i_cast_fu_307_p2.read(): p_shl_fu_299_p3.read());
}

void cal_mag_phase::thread_r_V_18_fu_342_p1() {
    r_V_18_fu_342_p1 = mt_i_cast_fu_332_p1.read();
}

void cal_mag_phase::thread_r_V_18_fu_342_p3() {
    r_V_18_fu_342_p3 = (!tmp_27_fu_291_p3.read()[0].is_01())? sc_lv<53>(): ((tmp_27_fu_291_p3.read()[0].to_bool())? r_V_18_fu_342_p1.read(): mf_i_fu_336_p2.read());
}

void cal_mag_phase::thread_r_V_20_fu_464_p2() {
    r_V_20_fu_464_p2 = (!lhs_V_cast_fu_456_p1.read().is_01() || !rhs_V2_i_fu_460_p1.read().is_01())? sc_lv<65>(): (sc_bigint<65>(lhs_V_cast_fu_456_p1.read()) - sc_biguint<65>(rhs_V2_i_fu_460_p1.read()));
}

void cal_mag_phase::thread_r_V_22_fu_489_p2() {
    r_V_22_fu_489_p2 = (!lhs_V_1_cast_fu_481_p1.read().is_01() || !rhs_V_203_i_fu_485_p1.read().is_01())? sc_lv<65>(): (sc_bigint<65>(lhs_V_1_cast_fu_481_p1.read()) + sc_biguint<65>(rhs_V_203_i_fu_485_p1.read()));
}

void cal_mag_phase::thread_r_V_23_fu_607_p2() {
    r_V_23_fu_607_p2 = (!p_Val2_29_reg_234.read().is_01() || !sh_assign_1_i_cast_fu_603_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(p_Val2_29_reg_234.read()) >> (unsigned short)sh_assign_1_i_cast_fu_603_p1.read().to_uint();
}

void cal_mag_phase::thread_r_V_24_fu_619_p2() {
    r_V_24_fu_619_p2 = (!t_V_4_reg_243.read().is_01() || !sh_assign_1_i_cast_fu_603_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(t_V_4_reg_243.read()) >> (unsigned short)sh_assign_1_i_cast_fu_603_p1.read().to_uint();
}

void cal_mag_phase::thread_r_V_48_cast_fu_321_p1() {
    r_V_48_cast_fu_321_p1 = esl_zext<65,52>(r_V_17_fu_313_p3.read());
}

void cal_mag_phase::thread_r_V_7_fu_392_p2() {
    r_V_7_fu_392_p2 = (!ai_V_1_reg_191.read().is_01() || !sh_assign_5_cast_cast_fu_388_p1.read().is_01())? sc_lv<22>(): sc_bigint<22>(ai_V_1_reg_191.read()) >> (unsigned short)sh_assign_5_cast_cast_fu_388_p1.read().to_uint();
}

void cal_mag_phase::thread_r_V_fu_671_p2() {
    r_V_fu_671_p2 = (!p_Val2_31_reg_221.read().is_01() || !ap_const_lv32_3243F6.is_01())? sc_lv<32>(): (sc_bigint<32>(p_Val2_31_reg_221.read()) + sc_biguint<32>(ap_const_lv32_3243F6));
}

void cal_mag_phase::thread_r_V_i_fu_705_p2() {
    r_V_i_fu_705_p2 = (!p_Val2_31_reg_221.read().is_01() || !p_Val2_7_i_cast_fu_701_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_Val2_31_reg_221.read()) - sc_biguint<32>(p_Val2_7_i_cast_fu_701_p1.read()));
}

void cal_mag_phase::thread_r_V_s_fu_694_p2() {
    r_V_s_fu_694_p2 = (!p_Val2_31_reg_221.read().is_01() || !ap_const_lv32_FFCDBC0A.is_01())? sc_lv<32>(): (sc_bigint<32>(p_Val2_31_reg_221.read()) + sc_biguint<32>(ap_const_lv32_FFCDBC0A));
}

void cal_mag_phase::thread_real_V_address0() {
    real_V_address0 =  (sc_lv<10>) (tmp_fu_286_p1.read());
}

void cal_mag_phase::thread_real_V_ce0() {
    if ((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond6_fu_274_p2.read(), ap_const_lv1_0))) {
        real_V_ce0 = ap_const_logic_1;
    } else {
        real_V_ce0 = ap_const_logic_0;
    }
}

void cal_mag_phase::thread_rhs_V2_i_fu_460_p0() {
    rhs_V2_i_fu_460_p0 = esl_sext<64,54>(r_V_19_reg_843.read());
}

void cal_mag_phase::thread_rhs_V2_i_fu_460_p1() {
    rhs_V2_i_fu_460_p1 = esl_zext<65,64>(rhs_V2_i_fu_460_p0.read());
}

void cal_mag_phase::thread_rhs_V_203_i_fu_485_p0() {
    rhs_V_203_i_fu_485_p0 = esl_sext<64,54>(r_V_21_reg_848.read());
}

void cal_mag_phase::thread_rhs_V_203_i_fu_485_p1() {
    rhs_V_203_i_fu_485_p1 = esl_zext<65,64>(rhs_V_203_i_fu_485_p0.read());
}

void cal_mag_phase::thread_sel_i_fu_526_p3() {
    sel_i_fu_526_p3 = (!tmp_29_reg_821.read()[0].is_01())? sc_lv<105>(): ((tmp_29_reg_821.read()[0].to_bool())? neg_mul_i_fu_521_p2.read(): mul_i_reg_868.read());
}

void cal_mag_phase::thread_sh_assign_1_i_cast_fu_603_p1() {
    sh_assign_1_i_cast_fu_603_p1 = esl_zext<32,7>(step_2_reg_252.read());
}

void cal_mag_phase::thread_sh_assign_5_cast_cast_fu_388_p1() {
    sh_assign_5_cast_cast_fu_388_p1 = esl_zext<22,7>(i_2_reg_210.read());
}

void cal_mag_phase::thread_step_fu_589_p2() {
    step_fu_589_p2 = (!step_2_reg_252.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_bigint<7>(step_2_reg_252.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void cal_mag_phase::thread_storemerge_i_fu_717_p3() {
    storemerge_i_fu_717_p3 = (!tmp_31_reg_902.read()[0].is_01())? sc_lv<32>(): ((tmp_31_reg_902.read()[0].to_bool())? r_V_i_fu_705_p2.read(): r_V_12_i_fu_711_p2.read());
}

void cal_mag_phase::thread_t_V_fu_398_p3() {
    t_V_fu_398_p3 = esl_concat<32,20>(grp_fu_264_p4.read(), ap_const_lv20_0);
}

void cal_mag_phase::thread_tmp_27_fu_291_p3() {
    tmp_27_fu_291_p3 = imag_V_q0.read().range(31, 31);
}

void cal_mag_phase::thread_tmp_28_fu_360_p3() {
    tmp_28_fu_360_p3 = r_V_18_fu_342_p3.read().range(51, 51);
}

void cal_mag_phase::thread_tmp_30_fu_505_p3() {
    tmp_30_fu_505_p3 = r_V_22_fu_489_p2.read().range(51, 51);
}

void cal_mag_phase::thread_tmp_31_fu_595_p3() {
    tmp_31_fu_595_p3 = p_Val2_29_reg_234.read().range(31, 31);
}

void cal_mag_phase::thread_tmp_32_fu_664_p3() {
    tmp_32_fu_664_p3 = p_Val2_20_reg_756.read().range(31, 31);
}

void cal_mag_phase::thread_tmp_6_i_fu_631_p1() {
    tmp_6_i_fu_631_p1 = esl_zext<64,7>(step_2_reg_252.read());
}

void cal_mag_phase::thread_tmp_fu_286_p1() {
    tmp_fu_286_p1 = esl_zext<64,11>(i_reg_163.read());
}

void cal_mag_phase::thread_tmp_i3_fu_554_p2() {
    tmp_i3_fu_554_p2 = (!p_Val2_20_reg_756.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(p_Val2_20_reg_756.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void cal_mag_phase::thread_x_iteration_V_1_fu_576_p3() {
    x_iteration_V_1_fu_576_p3 = (!tmp_i3_fu_554_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_i3_fu_554_p2.read()[0].to_bool())? p_Val2_20_reg_756.read(): x_iteration_V_fu_559_p2.read());
}

void cal_mag_phase::thread_x_iteration_V_3_fu_613_p2() {
    x_iteration_V_3_fu_613_p2 = (!t_V_4_reg_243.read().is_01() || !r_V_23_fu_607_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(t_V_4_reg_243.read()) - sc_biguint<32>(r_V_23_fu_607_p2.read()));
}

void cal_mag_phase::thread_x_iteration_V_4_fu_636_p2() {
    x_iteration_V_4_fu_636_p2 = (!r_V_23_fu_607_p2.read().is_01() || !t_V_4_reg_243.read().is_01())? sc_lv<32>(): (sc_bigint<32>(r_V_23_fu_607_p2.read()) + sc_biguint<32>(t_V_4_reg_243.read()));
}

void cal_mag_phase::thread_x_iteration_V_5_fu_656_p3() {
    x_iteration_V_5_fu_656_p3 = (!tmp_31_fu_595_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_31_fu_595_p3.read()[0].to_bool())? x_iteration_V_3_fu_613_p2.read(): x_iteration_V_4_fu_636_p2.read());
}

void cal_mag_phase::thread_x_iteration_V_fu_559_p2() {
    x_iteration_V_fu_559_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_20_reg_756.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_20_reg_756.read()));
}

void cal_mag_phase::thread_y_iteration_V_1_fu_564_p2() {
    y_iteration_V_1_fu_564_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_21_reg_771.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_21_reg_771.read()));
}

void cal_mag_phase::thread_y_iteration_V_2_fu_569_p3() {
    y_iteration_V_2_fu_569_p3 = (!tmp_i3_fu_554_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_i3_fu_554_p2.read()[0].to_bool())? p_Val2_21_reg_771.read(): y_iteration_V_1_fu_564_p2.read());
}

void cal_mag_phase::thread_y_iteration_V_4_fu_642_p2() {
    y_iteration_V_4_fu_642_p2 = (!p_Val2_29_reg_234.read().is_01() || !r_V_24_fu_619_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_Val2_29_reg_234.read()) - sc_biguint<32>(r_V_24_fu_619_p2.read()));
}

void cal_mag_phase::thread_y_iteration_V_5_fu_648_p3() {
    y_iteration_V_5_fu_648_p3 = (!tmp_31_fu_595_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_31_fu_595_p3.read()[0].to_bool())? y_iteration_V_fu_625_p2.read(): y_iteration_V_4_fu_642_p2.read());
}

void cal_mag_phase::thread_y_iteration_V_fu_625_p2() {
    y_iteration_V_fu_625_p2 = (!r_V_24_fu_619_p2.read().is_01() || !p_Val2_29_reg_234.read().is_01())? sc_lv<32>(): (sc_bigint<32>(r_V_24_fu_619_p2.read()) + sc_biguint<32>(p_Val2_29_reg_234.read()));
}

void cal_mag_phase::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (!esl_seteq<1,1,1>(exitcond6_fu_274_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_376_p2.read())) {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 21 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_583_p2.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st23_fsm_22;
            }
            break;
        case 22 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}
}

