// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

module top_mul_38s_39ns_77_5_Mul5S_0(clk, ce, a, b, p);
input clk;
input ce;
input[38 - 1 : 0] a; // synthesis attribute keep a "true"
input[39 - 1 : 0] b; // synthesis attribute keep b "true"
output[77 - 1 : 0] p;
reg[38 - 1 : 0] a_reg;
reg[39 - 1 : 0] b_reg;
wire [77 - 1 : 0] tmp_product;
reg[77 - 1 : 0] buff0;
reg[77 - 1 : 0] buff1;
reg[77 - 1 : 0] buff2;

assign p = buff2;
assign tmp_product = $signed(a_reg) * $signed({1'b0, b_reg});
always @ (posedge clk) begin
    if (ce) begin
        a_reg <= a;
        b_reg <= b;
        buff0 <= tmp_product;
        buff1 <= buff0;
        buff2 <= buff1;
    end
end
endmodule

`timescale 1 ns / 1 ps
module top_mul_38s_39ns_77_5(
    clk,
    reset,
    ce,
    din0,
    din1,
    dout);

parameter ID = 32'd1;
parameter NUM_STAGE = 32'd1;
parameter din0_WIDTH = 32'd1;
parameter din1_WIDTH = 32'd1;
parameter dout_WIDTH = 32'd1;
input clk;
input reset;
input ce;
input[din0_WIDTH - 1:0] din0;
input[din1_WIDTH - 1:0] din1;
output[dout_WIDTH - 1:0] dout;




top_mul_38s_39ns_77_5_Mul5S_0 top_mul_38s_39ns_77_5_Mul5S_0_U(
    .clk( clk ),
    .ce( ce ),
    .a( din0 ),
    .b( din1 ),
    .p( dout ));

endmodule

